// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOgR-ehTeE7oA5j30He8WvzhMFtB0SWK0',
    appId: '1:615066626803:web:8ec262867b53df6a15a586',
    messagingSenderId: '615066626803',
    projectId: 'study-app-97977',
    authDomain: 'study-app-97977.firebaseapp.com',
    storageBucket: 'study-app-97977.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBANbG3Czu8pcmEDcIC5bw1aTOOcrsnWTc',
    appId: '1:615066626803:android:400e73b41a3da16b15a586',
    messagingSenderId: '615066626803',
    projectId: 'study-app-97977',
    storageBucket: 'study-app-97977.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8MTZImMdzM6-aeeZZAjU02am9GkST2O4',
    appId: '1:615066626803:ios:4e88c505c6e5481e15a586',
    messagingSenderId: '615066626803',
    projectId: 'study-app-97977',
    storageBucket: 'study-app-97977.appspot.com',
    iosClientId: '615066626803-4jitf7rb5da63g1ikm951if3tfle77pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8MTZImMdzM6-aeeZZAjU02am9GkST2O4',
    appId: '1:615066626803:ios:4e88c505c6e5481e15a586',
    messagingSenderId: '615066626803',
    projectId: 'study-app-97977',
    storageBucket: 'study-app-97977.appspot.com',
    iosClientId: '615066626803-4jitf7rb5da63g1ikm951if3tfle77pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyapp',
  );
}
